### ISSUE TITLE
Missing classes in inheritance and overrides?

### ISSUE THREAD

**Issue by brian428** [Dretch/typescript-declarations-for-ext#2]
Just FYI, I think your TSD generation logic is missing some items.

As a quick example, check out Ext.slider.Multi.setValue() (http://docs.sencha.com/extjs/4.2.1/#!/api/Ext.slider.Multi-method-setValue). This is overridden in Multi to take additional arguments. This overrides Ext.form.field.Base.setValue(). Neither of these is defined in the TSD...so Multi has no setValue() method at all in the TSD.

That's just a quick example, but there are probably more. Just wanted to give you a heads up.

**Comment by Dretch** [comment]
I don't think supporting methods being overriden in subclasses with different arguments is possible in the general case without the declaration generator understanding the Typescript type system more deeply.

At the moment I don't think that is worth the effort, so I am closing this issue as Wont-Fix.
