### ISSUE TITLE
Duplicate parameters names

### ISSUE THREAD

**Issue by madreason** [Dretch/typescript-declarations-for-ext#5]
```javascript
// Ext 5.1.0 has some duplicate parameter names!
while (prevParamNames[paramName]) {
    paramName = '_' + paramName;
}
```
This code isn't correct.

JS doesn't allow to define equal parameters names. ExtJS documentation contains many errors. And this mistake occurs in one place:
> Ext.app.BaseController.redirectTo(token, token, force): boolean.

But if you look to the implementation of the class, you can see one "token" parameter.

[http://docs.sencha.com/extjs/5.1/5.1.0-apidocs/source/BaseController.html#Ext-app-BaseController-method-redirectTo](http://docs.sencha.com/extjs/5.1/5.1.0-apidocs/source/BaseController.html#Ext-app-BaseController-method-redirectTo)

**Comment by Dretch** [comment]
I think I understand. Please close this issue if you are happy with the fix.

**Comment by madreason** [comment]
Fixed.
I recommend to make the system, which will be patch original documentation, like external json file linked to Ext version.
Now, i'm using this patch:
>addRewriteMethod( "Ext.app.BaseController", "redirectTo", ["name": "redirectTo", "params": [["name": "token", "type": "any"], ["name": "force", "type": "boolean"]], "return": ["type": "boolean"]] )

 in fork from generator:

[https://github.com/brian428/ext-typescript-generator](https://github.com/brian428/ext-typescript-generator)

**Comment by Dretch** [comment]
I agree a patch system would be useful. I might work on it at some point. :)
